/**
 * AUTO-GENERATED by scripts/extract-detail-patterns.ts
 * Do not edit manually.
 *
 * Tileset: ground_grass_details (21 columns x 18 rows)
 *   Rows 0-7  (tileIds 0-167)   = ground details
 *   Rows 8-17 (tileIds 168-377) = grass details
 *
 * Tileset: village_home (17 columns)
 *   flowerStamps: tile IDs 897-944 (rows 52-55)
 *
 * Ground stamps: 5
 * Grass stamps:  26
 * Flower stamps: 19
 */

import { DetailStamp } from "../types/generation";

export const groundStamps: DetailStamp[] = [
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 0, tileId: 10 },
      { dx: 1, dy: 0, tileId: 11 },
      { dx: 0, dy: 1, tileId: 31 },
      { dx: 1, dy: 1, tileId: 32 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 1, dy: 1, tileId: 86 },
      { dx: 0, dy: 0, tileId: 84 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 1, tileId: 155 },
      { dx: 0, dy: 0, tileId: 134 },
      { dx: 1, dy: 0, tileId: 135 },
      { dx: 1, dy: 1, tileId: 156 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 1, tileId: 88 },
      { dx: 1, dy: 0, tileId: 93 },
  ] },
  { width: 1, height: 2, tiles: [
      { dx: 0, dy: 0, tileId: 94 },
      { dx: 0, dy: 1, tileId: 90 },
  ] },
];

export const grassStamps: DetailStamp[] = [
  { width: 3, height: 5, tiles: [
      { dx: 0, dy: 0, tileId: 195 },
      { dx: 1, dy: 0, tileId: 196 },
      { dx: 0, dy: 1, tileId: 216 },
      { dx: 1, dy: 2, tileId: 288 },
      { dx: 2, dy: 2, tileId: 289 },
      { dx: 0, dy: 3, tileId: 299 },
      { dx: 1, dy: 3, tileId: 300 },
      { dx: 2, dy: 3, tileId: 310 },
      { dx: 1, dy: 4, tileId: 321 },
  ] },
  { width: 3, height: 2, tiles: [
      { dx: 1, dy: 1, tileId: 362 },
      { dx: 0, dy: 0, tileId: 340 },
      { dx: 1, dy: 0, tileId: 341 },
      { dx: 2, dy: 0, tileId: 342 },
      { dx: 0, dy: 1, tileId: 361 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 1, dy: 0, tileId: 289 },
      { dx: 0, dy: 0, tileId: 288 },
      { dx: 1, dy: 1, tileId: 310 },
  ] },
  { width: 4, height: 4, tiles: [
      { dx: 3, dy: 2, tileId: 365 },
      { dx: 3, dy: 1, tileId: 344 },
      { dx: 2, dy: 2, tileId: 247 },
      { dx: 2, dy: 0, tileId: 308 },
      { dx: 1, dy: 2, tileId: 246 },
      { dx: 1, dy: 3, tileId: 267 },
      { dx: 0, dy: 2, tileId: 312 },
  ] },
  { width: 2, height: 3, tiles: [
      { dx: 1, dy: 1, tileId: 270 },
      { dx: 1, dy: 0, tileId: 249 },
      { dx: 0, dy: 1, tileId: 269 },
      { dx: 0, dy: 2, tileId: 290 },
  ] },
  { width: 4, height: 3, tiles: [
      { dx: 1, dy: 2, tileId: 277 },
      { dx: 1, dy: 1, tileId: 256 },
      { dx: 2, dy: 1, tileId: 257 },
      { dx: 0, dy: 2, tileId: 276 },
      { dx: 2, dy: 2, tileId: 278 },
      { dx: 3, dy: 0, tileId: 243 },
  ] },
  { width: 3, height: 3, tiles: [
      { dx: 1, dy: 1, tileId: 203 },
      { dx: 1, dy: 0, tileId: 182 },
      { dx: 2, dy: 0, tileId: 183 },
      { dx: 0, dy: 1, tileId: 202 },
      { dx: 2, dy: 1, tileId: 204 },
      { dx: 0, dy: 2, tileId: 223 },
  ] },
  { width: 3, height: 2, tiles: [
      { dx: 2, dy: 1, tileId: 360 },
      { dx: 2, dy: 0, tileId: 339 },
      { dx: 1, dy: 1, tileId: 359 },
      { dx: 0, dy: 0, tileId: 338 },
  ] },
  { width: 2, height: 1, tiles: [
      { dx: 1, dy: 0, tileId: 243 },
      { dx: 0, dy: 0, tileId: 242 },
  ] },
  { width: 2, height: 3, tiles: [
      { dx: 0, dy: 0, tileId: 338 },
      { dx: 1, dy: 0, tileId: 339 },
      { dx: 1, dy: 1, tileId: 360 },
      { dx: 0, dy: 2, tileId: 359 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 1, dy: 1, tileId: 316 },
      { dx: 1, dy: 0, tileId: 295 },
      { dx: 0, dy: 1, tileId: 315 },
  ] },
  { width: 7, height: 4, tiles: [
      { dx: 3, dy: 1, tileId: 342 },
      { dx: 2, dy: 0, tileId: 284 },
      { dx: 2, dy: 1, tileId: 305 },
      { dx: 2, dy: 2, tileId: 362 },
      { dx: 4, dy: 2, tileId: 303 },
      { dx: 1, dy: 1, tileId: 300 },
      { dx: 1, dy: 2, tileId: 361 },
      { dx: 5, dy: 1, tileId: 269 },
      { dx: 5, dy: 2, tileId: 290 },
      { dx: 4, dy: 3, tileId: 324 },
      { dx: 0, dy: 0, tileId: 330 },
      { dx: 0, dy: 1, tileId: 299 },
      { dx: 6, dy: 0, tileId: 249 },
      { dx: 6, dy: 1, tileId: 270 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 0, tileId: 312 },
      { dx: 1, dy: 1, tileId: 331 },
  ] },
  { width: 5, height: 3, tiles: [
      { dx: 0, dy: 0, tileId: 330 },
      { dx: 1, dy: 1, tileId: 288 },
      { dx: 2, dy: 1, tileId: 289 },
      { dx: 2, dy: 2, tileId: 310 },
      { dx: 3, dy: 0, tileId: 246 },
      { dx: 3, dy: 1, tileId: 267 },
      { dx: 4, dy: 0, tileId: 247 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 1, tileId: 330 },
      { dx: 1, dy: 0, tileId: 331 },
  ] },
  { width: 2, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 330 },
      { dx: 1, dy: 0, tileId: 331 },
  ] },
  { width: 3, height: 2, tiles: [
      { dx: 2, dy: 0, tileId: 331 },
      { dx: 1, dy: 0, tileId: 245 },
      { dx: 1, dy: 1, tileId: 266 },
      { dx: 0, dy: 0, tileId: 244 },
  ] },
  { width: 1, height: 2, tiles: [
      { dx: 0, dy: 1, tileId: 270 },
      { dx: 0, dy: 0, tileId: 249 },
  ] },
  { width: 4, height: 4, tiles: [
      { dx: 0, dy: 0, tileId: 242 },
      { dx: 1, dy: 0, tileId: 243 },
      { dx: 0, dy: 1, tileId: 263 },
      { dx: 1, dy: 1, tileId: 264 },
      { dx: 2, dy: 2, tileId: 244 },
      { dx: 3, dy: 2, tileId: 245 },
      { dx: 3, dy: 3, tileId: 266 },
  ] },
  { width: 2, height: 3, tiles: [
      { dx: 0, dy: 1, tileId: 197 },
      { dx: 1, dy: 0, tileId: 177 },
      { dx: 1, dy: 1, tileId: 198 },
      { dx: 0, dy: 2, tileId: 218 },
  ] },
  { width: 12, height: 5, tiles: [
      { dx: 10, dy: 3, tileId: 244 },
      { dx: 9, dy: 2, tileId: 230 },
      { dx: 11, dy: 3, tileId: 245 },
      { dx: 11, dy: 4, tileId: 266 },
      { dx: 8, dy: 1, tileId: 208 },
      { dx: 9, dy: 1, tileId: 209 },
      { dx: 8, dy: 2, tileId: 229 },
      { dx: 7, dy: 0, tileId: 342 },
      { dx: 6, dy: 0, tileId: 341 },
      { dx: 6, dy: 1, tileId: 362 },
      { dx: 5, dy: 0, tileId: 340 },
      { dx: 5, dy: 1, tileId: 361 },
      { dx: 4, dy: 0, tileId: 249 },
      { dx: 4, dy: 1, tileId: 270 },
      { dx: 3, dy: 1, tileId: 269 },
      { dx: 3, dy: 2, tileId: 290 },
      { dx: 2, dy: 3, tileId: 341 },
      { dx: 3, dy: 3, tileId: 342 },
      { dx: 1, dy: 3, tileId: 300 },
      { dx: 1, dy: 4, tileId: 321 },
      { dx: 2, dy: 4, tileId: 362 },
      { dx: 0, dy: 4, tileId: 331 },
  ] },
  { width: 4, height: 4, tiles: [
      { dx: 1, dy: 3, tileId: 365 },
      { dx: 1, dy: 2, tileId: 344 },
      { dx: 0, dy: 3, tileId: 364 },
      { dx: 2, dy: 1, tileId: 324 },
      { dx: 2, dy: 0, tileId: 303 },
      { dx: 3, dy: 0, tileId: 330 },
      { dx: 3, dy: 1, tileId: 325 },
  ] },
  { width: 3, height: 3, tiles: [
      { dx: 2, dy: 1, tileId: 360 },
      { dx: 1, dy: 0, tileId: 338 },
      { dx: 2, dy: 0, tileId: 339 },
      { dx: 1, dy: 1, tileId: 304 },
      { dx: 1, dy: 2, tileId: 325 },
      { dx: 0, dy: 1, tileId: 303 },
      { dx: 0, dy: 2, tileId: 324 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 1, dy: 0, tileId: 245 },
      { dx: 0, dy: 0, tileId: 244 },
      { dx: 1, dy: 1, tileId: 266 },
  ] },
  { width: 3, height: 3, tiles: [
      { dx: 1, dy: 2, tileId: 365 },
      { dx: 1, dy: 1, tileId: 267 },
      { dx: 0, dy: 2, tileId: 364 },
      { dx: 1, dy: 0, tileId: 246 },
      { dx: 2, dy: 0, tileId: 247 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 1, dy: 0, tileId: 300 },
      { dx: 0, dy: 0, tileId: 299 },
      { dx: 1, dy: 1, tileId: 321 },
  ] },
];

export const flowerStamps: DetailStamp[] = [
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 927 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 925 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 922 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 923 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 939 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 897 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 931 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 930 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 944 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 0, tileId: 932 },
      { dx: 1, dy: 0, tileId: 933 },
      { dx: 0, dy: 1, tileId: 944 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 0, tileId: 927 },
      { dx: 1, dy: 1, tileId: 926 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 928 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 1, tileId: 938 },
      { dx: 0, dy: 0, tileId: 921 },
      { dx: 1, dy: 1, tileId: 922 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 0, tileId: 925 },
      { dx: 1, dy: 1, tileId: 924 },
  ] },
  { width: 1, height: 2, tiles: [
      { dx: 0, dy: 1, tileId: 897 },
      { dx: 0, dy: 0, tileId: 930 },
  ] },
  { width: 2, height: 1, tiles: [
      { dx: 1, dy: 0, tileId: 926 },
      { dx: 0, dy: 0, tileId: 925 },
  ] },
  { width: 2, height: 2, tiles: [
      { dx: 0, dy: 0, tileId: 944 },
      { dx: 1, dy: 1, tileId: 926 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 926 },
  ] },
  { width: 1, height: 1, tiles: [
      { dx: 0, dy: 0, tileId: 924 },
  ] },
];
