import { MapConfig, MapName, Spritesheet } from "../types";

const player: Spritesheet[] = [
  {
    key: "player-idle",
    file: "player_idle.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-walking",
    file: "player_walking.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-running",
    file: "player_running.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-jumping",
    file: "player_jumping.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-casting",
    file: "player_casting.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-rolling",
    file: "player_rolling.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-idle-lantern",
    file: "player_idle_with_lantern.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-walking-lantern",
    file: "player_walking_with_lantern.png",
    frameWidth: 32,
    frameHeight: 32,
  },
];

const animals: Spritesheet[] = [
  {
    key: "drake-idle",
    file: "drake_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "drake-walking",
    file: "drake_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "duck-idle",
    file: "duck_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "duck-walking",
    file: "duck_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "goose-idle",
    file: "goose_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "goose-walking",
    file: "goose_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "fox-idle",
    file: "fox_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "fox-walking",
    file: "fox_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "fox-running",
    file: "fox_running_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "deer-idle",
    file: "deer_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "deer-walking",
    file: "deer_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "deer-running",
    file: "deer_running_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-idle",
    file: "boar_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-walking",
    file: "boar_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-running",
    file: "boar_running_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-slashing",
    file: "boar_slashing_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
];

const plants: Spritesheet[] = [
  {
    key: "plants_bushes",
    file: "plants_bushes.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "reed",
    file: "reed.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "gathering1",
    file: "gathering1.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "gathering2",
    file: "gathering2.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "gathering3",
    file: "gathering3.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "gathering4",
    file: "gathering4.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "gathering5",
    file: "gathering5.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
];

const buildings: Spritesheet[] = [
  {
    key: "village_herbalist_house",
    file: "village_herbalist_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_farm_house",
    file: "village_farm_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_blacksmith_house",
    file: "village_blacksmith_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_tavern_house",
    file: "village_tavern_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_tavern_house",
    file: "village_tavern_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_glassblower_house",
    file: "village_glassblower_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_fishing_dock_house",
    file: "village_fishing_dock_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
];

const citizens: Spritesheet[] = [
  {
    key: "citizen1-idle",
    file: "citizen1_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen1-walking",
    file: "citizen1_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen2-idle",
    file: "citizen2_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen2-walking",
    file: "citizen2_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen3-idle",
    file: "citizen3_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen4-idle",
    file: "citizen4_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen5-idle",
    file: "citizen5_idle.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen6-idle",
    file: "citizen6_idle.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen7-idle",
    file: "citizen7_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen7-walking",
    file: "citizen7_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen8-idle",
    file: "citizen8_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen9-idle",
    file: "citizen9_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen10-idle",
    file: "citizen10_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen11-idle",
    file: "citizen11_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen12-idle",
    file: "citizen12_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen12-walking",
    file: "citizen12_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen13-idle",
    file: "citizen13_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen13-walking",
    file: "citizen13_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "baker-idle",
    file: "baker_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "beverage_saler-idle",
    file: "beverage_saler_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "greengrocer-idle",
    file: "greengrocer_idle.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "host-idle",
    file: "host_idle.png",
    frameWidth: 32,
    frameHeight: 32,
  },
];

const icons: Spritesheet[] = [
  {
    key: "icons1",
    file: "icons1.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "icons2",
    file: "icons2.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "icons3",
    file: "icons3.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "icons4",
    file: "icons4.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "icons5",
    file: "icons5.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "icons6",
    file: "icons6.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "icons7",
    file: "icons7.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
];

const interior: Spritesheet[] = [
  {
    key: "chests",
    file: "chests.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
];

const creatures: Spritesheet[] = [
  { key: "orc1-idle", file: "orc1_idle_with_shadow.png" },
  { key: "orc1-walking", file: "orc1_walking_with_shadow.png" },
  { key: "orc1-running", file: "orc1_running_with_shadow.png" },
  { key: "orc1-slashing", file: "orc1_slashing_with_shadow.png" },
  { key: "goblin1-idle", file: "goblin1_idle_with_shadow.png" },
  { key: "goblin1-walking", file: "goblin1_walking_with_shadow.png" },
  { key: "goblin1-running", file: "goblin1_running_with_shadow.png" },
  { key: "goblin1-slashing", file: "goblin1_slashing_with_shadow.png" },
  { key: "shadow_wanderer-idle", file: "shadow_wanderer_idle_with_shadow.png" },
  {
    key: "shadow_wanderer-walking",
    file: "shadow_wanderer_walking_with_shadow.png",
  },
  {
    key: "shadow_wanderer-dashing",
    file: "shadow_wanderer_dashing_with_shadow.png",
  },
  {
    key: "shadow_wanderer-casting",
    file: "shadow_wanderer_casting_with_shadow.png",
  },
];

export const maps: Record<MapName, MapConfig> = {
  [MapName.VILLAGE]: {
    id: MapName.VILLAGE,
    spawn: { x: 434, y: 608 },
    json: "village.json",
    isIndoor: false,
    spritesheets: [
      ...player,
      ...animals,
      ...plants,
      ...buildings,
      ...citizens,
      ...icons,
      ...creatures,
      ...interior,
      {
        key: "village_home",
        file: "village_home.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_farm_ground_grass",
        file: "village_farm_ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_market_objects",
        file: "village_market_objects.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_fishing_dock_boat1",
        file: "village_fishing_dock_boat1.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_fishing_dock_ground",
        file: "village_fishing_dock_ground.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass",
        file: "ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass_details",
        file: "ground_grass_details.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "crystals",
        file: "crystals.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "bridges",
        file: "bridges.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "water_coasts",
        file: "water_coasts.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "water_detilazation",
        file: "water_detilazation.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "water_lilis",
        file: "water_lilis.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "road_stone",
        file: "road_stone.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "road_walls_paving",
        file: "road_walls_paving.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.HERBALIST_HOUSE]: {
    id: MapName.HERBALIST_HOUSE,
    spawn: { x: 128, y: 168 },
    json: "herbalist_house.json",
    isIndoor: true,
    spritesheets: [
      ...player,
      {
        key: "village_herbalist_boiler",
        file: "village_herbalist_boiler.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_herbalist_interior",
        file: "village_herbalist_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_herbalist_walls_floor",
        file: "village_herbalist_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "herbalist-idle",
        file: "herbalist_idle.png",
        frameWidth: 32,
        frameHeight: 32,
      },
      {
        key: "herbalist-walking",
        file: "herbalist_walking.png",
        frameWidth: 32,
        frameHeight: 32,
      },
    ],
  },
  [MapName.BLACKSMITH_HOUSE]: {
    id: MapName.BLACKSMITH_HOUSE,
    spawn: { x: 128, y: 168 },
    json: "blacksmith_house.json",
    isIndoor: true,
    spritesheets: [
      ...player,
      {
        key: "village_blacksmith_walls_floor",
        file: "village_blacksmith_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_blacksmith_interior",
        file: "village_blacksmith_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "torch",
        file: "torch.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_blacksmith_forge",
        file: "village_blacksmith_forge.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "blacksmith-idle",
        file: "blacksmith_idle_with_shadow.png",
        frameWidth: 48,
        frameHeight: 48,
      },
      {
        key: "blacksmith-walking",
        file: "blacksmith_walking_with_shadow.png",
        frameWidth: 48,
        frameHeight: 48,
      },
    ],
  },
  [MapName.GLASSBLOWER_HOUSE]: {
    id: MapName.GLASSBLOWER_HOUSE,
    spawn: { x: 144, y: 272 },
    json: "glassblower_house.json",
    isIndoor: true,
    spritesheets: [
      ...player,
      {
        key: "village_glassblower_walls_floor",
        file: "village_glassblower_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_glassblower_forge",
        file: "village_glassblower_forge.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_glassblower_interior",
        file: "village_glassblower_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_glassblower_master",
        file: "village_glassblower_master.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "glassblower-idle",
        file: "glassblower_idle.png",
        frameWidth: 32,
        frameHeight: 32,
      },
    ],
  },
  [MapName.FISHING_HUT]: {
    id: MapName.FISHING_HUT,
    spawn: { x: 144, y: 272 },
    json: "fishing_hut.json",
    isIndoor: true,
    spritesheets: [
      ...player,
      {
        key: "village_fishing_dock_house_walls_floor",
        file: "village_fishing_dock_house_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_fishing_dock_interior",
        file: "village_fishing_dock_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.HOME]: {
    id: MapName.HOME,
    spawn: { x: 184, y: 168 },
    json: "home.json",
    isIndoor: true,
    spritesheets: [
      ...player,
      {
        key: "village_home_interior",
        file: "village_home_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_home_walls_floor",
        file: "village_home_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.TAVERN]: {
    id: MapName.TAVERN,
    spawn: { x: 128, y: 168 },
    json: "tavern.json",
    isIndoor: true,
    spritesheets: [
      ...player,
      ...citizens,
      {
        key: "village_tavern_interior",
        file: "village_tavern_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_tavern_walls_floor",
        file: "village_tavern_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.REALM]: {
    id: MapName.REALM,
    spawn: { x: 434, y: 608 },
    json: "",
    isIndoor: false,
    spritesheets: [
      ...player,
      ...animals,
      ...plants,
      ...creatures,
      ...interior,
      {
        key: "village_home",
        file: "village_home.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_farm_ground_grass",
        file: "village_farm_ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass",
        file: "ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass_details",
        file: "ground_grass_details.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "water_coasts",
        file: "water_coasts.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
};
