import { MapConfig, MapName, Spritesheet } from "../types";

const player: Spritesheet[] = [
  {
    key: "player-idle",
    file: "player_idle.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-walking",
    file: "player_walking.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-running",
    file: "player_running.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-jumping",
    file: "player_jumping.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-casting",
    file: "player_casting.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "player-rolling",
    file: "player_rolling.png",
    frameWidth: 32,
    frameHeight: 32,
  },
];

const animals: Spritesheet[] = [
  {
    key: "drake-idle",
    file: "drake_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "drake-walking",
    file: "drake_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "duck-idle",
    file: "duck_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "duck-walking",
    file: "duck_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "fox-idle",
    file: "fox_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "fox-walking",
    file: "fox_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "fox-running",
    file: "fox_running_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "deer-idle",
    file: "deer_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "deer-walking",
    file: "deer_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "deer-running",
    file: "deer_running_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-idle",
    file: "boar_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-walking",
    file: "boar_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-running",
    file: "boar_running_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "boar-slashing",
    file: "boar_slashing_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
];

const buildings: Spritesheet[] = [
  {
    key: "village_herbalist_house",
    file: "village_herbalist_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_farm_house",
    file: "village_farm_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_blacksmith_house",
    file: "village_blacksmith_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_tavern_house",
    file: "village_tavern_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_tavern_house",
    file: "village_tavern_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
  {
    key: "village_glassblower_house",
    file: "village_glassblower_house.png",
    frameWidth: 16,
    frameHeight: 16,
    asTileset: true,
  },
];

const citizens: Spritesheet[] = [
  {
    key: "citizen1-idle",
    file: "citizen1_idle_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
  {
    key: "citizen1-walking",
    file: "citizen1_walking_with_shadow.png",
    frameWidth: 32,
    frameHeight: 32,
  },
];

const creatures: Spritesheet[] = [
  { key: "orc1-idle", file: "orc1_idle_with_shadow.png" },
  { key: "orc1-walking", file: "orc1_walking_with_shadow.png" },
  { key: "orc1-running", file: "orc1_running_with_shadow.png" },
  { key: "orc1-slashing", file: "orc1_slashing_with_shadow.png" },
];

export const maps: Record<MapName, MapConfig> = {
  [MapName.VILLAGE]: {
    id: MapName.VILLAGE,
    spawn: { x: 434, y: 608 },
    json: "village.json",
    spritesheets: [
      ...player,
      ...animals,
      ...buildings,
      ...citizens,
      {
        key: "village_home",
        file: "village_home.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_farm_ground_grass",
        file: "village_farm_ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_market_objects",
        file: "village_market_objects.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass",
        file: "ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass_details",
        file: "ground_grass_details.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "plants_bushes",
        file: "plants_bushes.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "reed",
        file: "reed.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "bridges",
        file: "bridges.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "water_coasts",
        file: "water_coasts.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "road_stone",
        file: "road_stone.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "road_walls_paving",
        file: "road_walls_paving.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.HERBALIST_HOUSE]: {
    id: MapName.HERBALIST_HOUSE,
    spawn: { x: 128, y: 168 },
    json: "herbalist_house.json",
    spritesheets: [
      ...player,
      {
        key: "village_herbalist_boiler",
        file: "village_herbalist_boiler.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_herbalist_interior",
        file: "village_herbalist_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_herbalist_walls_floor",
        file: "village_herbalist_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "herbalist-idle",
        file: "herbalist_idle.png",
        frameWidth: 32,
        frameHeight: 32,
      },
      {
        key: "herbalist-walking",
        file: "herbalist_walking.png",
        frameWidth: 32,
        frameHeight: 32,
      },
    ],
  },
  [MapName.BLACKSMITH_HOUSE]: {
    id: MapName.BLACKSMITH_HOUSE,
    spawn: { x: 128, y: 168 },
    json: "blacksmith_house.json",
    spritesheets: [
      ...player,
      {
        key: "village_blacksmith_walls_floor",
        file: "village_blacksmith_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_blacksmith_interior",
        file: "village_blacksmith_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "torch",
        file: "torch.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_blacksmith_forge",
        file: "village_blacksmith_forge.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "blacksmith-idle",
        file: "blacksmith_idle_with_shadow.png",
        frameWidth: 48,
        frameHeight: 48,
      },
      {
        key: "blacksmith-walking",
        file: "blacksmith_walking_with_shadow.png",
        frameWidth: 48,
        frameHeight: 48,
      },
    ],
  },
  [MapName.GLASSBLOWER_HOUSE]: {
    id: MapName.GLASSBLOWER_HOUSE,
    spawn: { x: 128, y: 168 },
    json: "glassblower_house.json",
    spritesheets: [
      ...player,
      {
        key: "village_glassblower_walls_floor",
        file: "village_glassblower_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.HOME]: {
    id: MapName.HOME,
    spawn: { x: 184, y: 168 },
    json: "home.json",
    spritesheets: [
      ...player,
      {
        key: "village_home_interior",
        file: "village_home_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_home_walls_floor",
        file: "village_home_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.TAVERN]: {
    id: MapName.TAVERN,
    spawn: { x: 128, y: 168 },
    json: "tavern.json",
    spritesheets: [
      ...player,
      {
        key: "village_tavern_interior",
        file: "village_tavern_interior.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_tavern_walls_floor",
        file: "village_tavern_walls_floor.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
  [MapName.REALM]: {
    id: MapName.REALM,
    spawn: { x: 434, y: 608 },
    json: "",
    spritesheets: [
      ...player,
      ...animals,
      ...creatures,
      {
        key: "village_home",
        file: "village_home.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "village_farm_ground_grass",
        file: "village_farm_ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass",
        file: "ground_grass.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "ground_grass_details",
        file: "ground_grass_details.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "plants_bushes",
        file: "plants_bushes.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "reed",
        file: "reed.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
      {
        key: "water_coasts",
        file: "water_coasts.png",
        frameWidth: 16,
        frameHeight: 16,
        asTileset: true,
      },
    ],
  },
};
